//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public int PLRNO { get; set; }
        public string PLRNAME { get; set; }
        public string GAME { get; set; }
        public string COUNTRY { get; set; }
    }
}
